<?php
/**
 * Copyright 2026 Tecnoacquisti.com
 *
 * @author    Tecnoacquisti.com <helpdesk@tecnoacquisti.com>
 * @copyright 2026 Tecnoacquisti.com
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 * @version   1.0.0
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

require_once __DIR__ . '/src/CloudflareClient.php';

/**
 * Purges Cloudflare cache and manages safe cache bypass rules.
 */
class Teccloudflarecache extends Module
{
    const CFG_TOKEN = 'TECCFC_TOKEN';
    const CFG_ZONE_ID = 'TECCFC_ZONE_ID';
    const CFG_ZONE_NAME = 'TECCFC_ZONE_NAME';
    const CFG_SYNC_WITH_PS = 'TECCFC_SYNC_WITH_PS';
    const CFG_BYPASS_ADMIN = 'TECCFC_BYPASS_ADMIN';
    const CFG_BYPASS_URLS = 'TECCFC_BYPASS_URLS';
    const CFG_MONITOR_URL = 'TECCFC_MONITOR_URL';
    const CFG_LAST_STATUS = 'TECCFC_LAST_STATUS';
    const TOKEN_MASK = '********';

    /**
     * Prevents duplicate purge calls during the current PHP request.
     *
     * @var bool
     */
    private static $purgeHandled = false;

    /**
     * Initializes module metadata.
     */
    public function __construct()
    {
        $this->name = 'teccloudflarecache';
        $this->tab = 'administration';
        $this->version = '1.0.0';
        $this->author = 'Tecnoacquisti.com';
        $this->need_instance = 0;
        $this->bootstrap = true;
        $this->ps_versions_compliancy = [
            'min' => '1.7.0',
            'max' => '9.99.99',
        ];

        parent::__construct();

        $this->displayName = $this->l('Tec Cloudflare Cache');
        $this->description = $this->l('Purge and monitor Cloudflare cache from PrestaShop.');
        $this->confirmUninstall = $this->l('Uninstall Tec Cloudflare Cache?');
    }

    /**
     * Installs configuration defaults and available PrestaShop hooks.
     *
     * @return bool Whether installation completed successfully
     */
    public function install()
    {
        if (!parent::install()) {
            return false;
        }

        foreach ([
            self::CFG_TOKEN => '',
            self::CFG_ZONE_ID => '',
            self::CFG_ZONE_NAME => '',
            self::CFG_SYNC_WITH_PS => 0,
            self::CFG_BYPASS_ADMIN => 0,
            self::CFG_BYPASS_URLS => '',
            self::CFG_MONITOR_URL => '',
            self::CFG_LAST_STATUS => '',
        ] as $key => $value) {
            if (!Configuration::updateValue($key, $value)) {
                return false;
            }
        }

        foreach (['actionClearCache', 'actionAdminPerformanceSave'] as $hookName) {
            if ((int) Hook::getIdByName($hookName) > 0 && !$this->registerHook($hookName)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Deletes saved module configuration.
     *
     * @return bool Whether uninstallation completed successfully
     */
    public function uninstall()
    {
        foreach ([
            self::CFG_TOKEN,
            self::CFG_ZONE_ID,
            self::CFG_ZONE_NAME,
            self::CFG_SYNC_WITH_PS,
            self::CFG_BYPASS_ADMIN,
            self::CFG_BYPASS_URLS,
            self::CFG_MONITOR_URL,
            self::CFG_LAST_STATUS,
        ] as $key) {
            Configuration::deleteByName($key);
        }

        return parent::uninstall();
    }

    /**
     * Purges Cloudflare after PrestaShop clears its cache.
     *
     * @param array $params Hook parameters
     *
     * @return void
     */
    public function hookActionClearCache($params)
    {
        $this->purgeAfterPrestaShopCacheClear();
    }

    /**
     * Handles a cache clear initiated from the Performance page.
     *
     * @param array $params Hook parameters
     *
     * @return void
     */
    public function hookActionAdminPerformanceSave($params)
    {
        $this->purgeAfterPrestaShopCacheClear();
    }

    /**
     * Renders and processes the legacy configuration page for all supported versions.
     *
     * @return string Back-office HTML generated by PrestaShop HelperForm
     */
    public function getContent()
    {
        $output = '';

        if (Tools::isSubmit('tec_cf_save')) {
            $errors = $this->saveConfiguration();
            $output .= $this->formatErrors($errors);
            if (!$errors) {
                $output .= $this->displayConfirmation($this->l('Configuration saved.'));
            }
        }

        if (Tools::isSubmit('tec_cf_test')) {
            $result = $this->getClient()->verifyConnection();
            $output .= $result['success']
                ? $this->displayConfirmation($this->l('Cloudflare connection verified.'))
                : $this->displayError($this->l('Cloudflare connection failed: ') . $result['message']);
        }

        if (Tools::isSubmit('tec_cf_purge')) {
            $result = $this->purgeCloudflare('manual');
            $output .= $result['success']
                ? $this->displayConfirmation($this->l('Cloudflare cache purge requested.'))
                : $this->displayError($this->l('Cloudflare cache purge failed: ') . $result['message']);
        }

        if (Tools::isSubmit('tec_cf_monitor')) {
            $result = $this->testStorefrontCache();
            $output .= $result['success']
                ? $this->displayConfirmation($result['message'])
                : $this->displayError($result['message']);
        }

        if (Tools::isSubmit('tec_cf_apply_rules')) {
            $errors = $this->saveConfiguration();
            if ($errors) {
                $output .= $this->formatErrors($errors);
            } else {
                $result = $this->applyBypassRules();
                $output .= $result['success']
                    ? $this->displayConfirmation($this->l('Cloudflare bypass rules applied.'))
                    : $this->displayError($this->l('Cloudflare rules were not changed: ') . $result['message']);
            }
        }

        return $output . $this->renderConfigurationForm();
    }

    /**
     * Runs a non-blocking purge from cache-clear hooks.
     *
     * @return void
     */
    private function purgeAfterPrestaShopCacheClear()
    {
        if (self::$purgeHandled || !(bool) Configuration::get(self::CFG_SYNC_WITH_PS)) {
            return;
        }

        self::$purgeHandled = true;
        $result = $this->purgeCloudflare('prestashop-cache-clear');
        if (!$result['success']) {
            $this->log('Cloudflare purge skipped or failed: ' . $result['message'], 2);
        }
    }

    /**
     * Requests a full zone purge and records a safe status message.
     *
     * @param string $source Origin of the purge request
     *
     * @return array{success: bool, message: string}
     */
    private function purgeCloudflare($source)
    {
        if (!$this->isCloudflareConfigured()) {
            return ['success' => false, 'message' => $this->l('API token or Zone ID is not configured.')];
        }

        $result = $this->getClient()->purgeEverything();
        $status = $source . ': ' . ($result['success'] ? 'success' : 'failed') . ' - ' . $result['message'];
        Configuration::updateValue(self::CFG_LAST_STATUS, $status);
        $this->log('Cloudflare purge ' . $status, $result['success'] ? 1 : 2);

        return $result;
    }

    /**
     * Checks the public storefront response for Cloudflare cache headers.
     *
     * @return array{success: bool, message: string}
     */
    private function testStorefrontCache()
    {
        if (!function_exists('curl_init')) {
            return ['success' => false, 'message' => $this->l('The PHP cURL extension is required.')];
        }

        $url = (string) Configuration::get(self::CFG_MONITOR_URL);
        if ($url === '') {
            $url = $this->context->link->getPageLink('index', true);
        }
        $handle = curl_init($url);
        if ($handle === false) {
            return ['success' => false, 'message' => $this->l('Unable to initialize the HTTP client.')];
        }

        curl_setopt_array($handle, [
            CURLOPT_NOBODY => true,
            CURLOPT_HEADER => true,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => false,
            CURLOPT_CONNECTTIMEOUT => 5,
            CURLOPT_TIMEOUT => 15,
            CURLOPT_SSL_VERIFYPEER => true,
            CURLOPT_SSL_VERIFYHOST => 2,
        ]);
        $headers = curl_exec($handle);
        $status = (int) curl_getinfo($handle, CURLINFO_HTTP_CODE);
        $error = curl_error($handle);
        curl_close($handle);

        if ($headers === false) {
            return ['success' => false, 'message' => $this->l('Storefront cache check failed: ') . $this->sanitizeDiagnostic($error)];
        }
        if (!preg_match('/^CF-Cache-Status:\s*([^\r\n]+)/im', $headers, $matches)) {
            return [
                'success' => true,
                'message' => $this->l('No Cloudflare cache status header was returned. Configure a public URL served through the selected Cloudflare zone to test cache status.'),
            ];
        }
        $cacheStatus = strtoupper(trim($matches[1]));
        $age = 'n/a';
        if (preg_match('/^Age:\s*(\d+)/im', $headers, $ageMatches)) {
            $age = $ageMatches[1] . ' seconds';
        }

        return [
            'success' => true,
            'message' => sprintf($this->l('Storefront HTTP %d. CF-Cache-Status: %s. Age: %s.'), $status, $cacheStatus, $age),
        ];
    }

    /**
     * Applies only module-owned bypass cache rules without altering other rules.
     *
     * @return array{success: bool, message: string}
     */
    private function applyBypassRules()
    {
        if (!$this->isCloudflareConfigured()) {
            return ['success' => false, 'message' => $this->l('API token or Zone ID is not configured.')];
        }

        if ((bool) Configuration::get(self::CFG_BYPASS_ADMIN) && !$this->isCurrentStoreInConfiguredZone()) {
            return [
                'success' => false,
                'message' => $this->l('The current PrestaShop host does not belong to the configured Cloudflare zone. Disable Back Office exclusion or configure this store for that zone.'),
            ];
        }

        $rules = $this->buildManagedRules();
        $client = $this->getClient();
        $existing = $client->getCacheRuleset();
        if (!$existing['success']) {
            return $existing;
        }

        $preservedRules = [];
        foreach ($existing['rules'] as $rule) {
            if (!isset($rule['description']) || strpos((string) $rule['description'], 'teccloudflarecache:') !== 0) {
                $preservedRules[] = $rule;
            }
        }

        if (count($preservedRules) + count($rules) > 10) {
            return [
                'success' => false,
                'message' => sprintf(
                    $this->l('The Free plan limit is 10 Cache Rules. Existing rules: %d. Requested module rules: %d.'),
                    count($preservedRules),
                    count($rules)
                ),
            ];
        }

        $result = $client->replaceCacheRules(
            array_merge($preservedRules, $rules),
            isset($existing['ruleset']) && is_array($existing['ruleset']) ? $existing['ruleset'] : []
        );
        if (!$result['success']) {
            $this->log('Cloudflare bypass rules failed: ' . $result['message'], 2);
        }

        return $result;
    }

    /**
     * Builds Cache Rules API payloads for configured safe exclusions.
     *
     * @return array<int, array<string, mixed>> Rules owned by this module
     */
    private function buildManagedRules()
    {
        $rules = [];
        if ((bool) Configuration::get(self::CFG_BYPASS_ADMIN)) {
            $adminDirectory = basename((string) _PS_ADMIN_DIR_);
            $rules[] = $this->buildBypassRule(
                'admin',
                '(http.request.uri.path starts_with "/' . $this->escapeExpressionString($adminDirectory) . '")'
            );
        }

        foreach ($this->getConfiguredUrls() as $url) {
            $parts = parse_url($url);
            $host = strtolower((string) $parts['host']);
            $path = isset($parts['path']) ? (string) $parts['path'] : '/';
            $expression = '(http.host eq "' . $this->escapeExpressionString($host) . '" and http.request.uri.path wildcard "'
                . $this->escapeExpressionString($path) . '")';
            $rules[] = $this->buildBypassRule('url-' . sha1($url), $expression);
        }

        return $rules;
    }

    /**
     * Creates one Cloudflare bypass rule payload.
     *
     * @param string $identifier Stable module rule identifier
     * @param string $expression Cloudflare Rules language expression
     *
     * @return array<string, mixed> Rule payload
     */
    private function buildBypassRule($identifier, $expression)
    {
        return [
            'description' => 'teccloudflarecache:' . $identifier,
            'expression' => $expression,
            'action' => 'set_cache_settings',
            'action_parameters' => [
                'cache' => false,
            ],
            'enabled' => true,
        ];
    }

    /**
     * Saves validated configuration values and preserves a masked token.
     *
     * @return string[] Validation error messages
     */
    private function saveConfiguration()
    {
        $errors = [];
        $token = trim((string) Tools::getValue('TECCFC_TOKEN'));
        $zoneId = strtolower(trim((string) Tools::getValue('TECCFC_ZONE_ID')));
        $zoneName = strtolower(trim((string) Tools::getValue('TECCFC_ZONE_NAME')));
        $urls = trim((string) Tools::getValue('TECCFC_BYPASS_URLS'));
        $monitorUrl = trim((string) Tools::getValue('TECCFC_MONITOR_URL'));

        if ($token !== '' && strpos($token, self::TOKEN_MASK) === false && !preg_match('/^[A-Za-z0-9._~-]{20,300}$/', $token)) {
            $errors[] = $this->l('The API token format is invalid.');
        }
        if ($zoneId !== '' && !preg_match('/^[a-f0-9]{32}$/', $zoneId)) {
            $errors[] = $this->l('The Zone ID must contain 32 hexadecimal characters.');
        }
        if ($zoneName !== '' && !preg_match('/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/', $zoneName)) {
            $errors[] = $this->l('The Zone name is invalid.');
        }

        $validatedUrls = $this->validateBypassUrls($urls, $zoneName, $errors);
        $validatedMonitorUrl = $this->validateMonitorUrl($monitorUrl, $zoneName, $errors);
        if ($errors) {
            return $errors;
        }

        if ($token !== '' && strpos($token, self::TOKEN_MASK) === false) {
            Configuration::updateValue(self::CFG_TOKEN, $token);
        }
        Configuration::updateValue(self::CFG_ZONE_ID, $zoneId);
        Configuration::updateValue(self::CFG_ZONE_NAME, $zoneName);
        Configuration::updateValue(self::CFG_SYNC_WITH_PS, (int) (bool) Tools::getValue('TECCFC_SYNC_WITH_PS'));
        Configuration::updateValue(self::CFG_BYPASS_ADMIN, (int) (bool) Tools::getValue('TECCFC_BYPASS_ADMIN'));
        Configuration::updateValue(self::CFG_BYPASS_URLS, implode("\n", $validatedUrls));
        Configuration::updateValue(self::CFG_MONITOR_URL, $validatedMonitorUrl);

        return [];
    }

    /**
     * Validates newline-separated full URLs and trailing path wildcards.
     *
     * @param string $value Submitted textarea content
     * @param string $zoneName Configured Cloudflare zone name
     * @param string[] $errors Validation errors appended by reference
     *
     * @return string[] Normalized and unique URLs
     */
    private function validateBypassUrls($value, $zoneName, &$errors)
    {
        $urls = [];
        foreach (preg_split('/\R/', $value) as $line) {
            $url = trim($line);
            if ($url === '') {
                continue;
            }
            if (strlen($url) > 2048 || preg_match('/[\x00-\x1F\x7F]/', $url)) {
                $errors[] = $this->l('Each bypass URL must be a safe URL no longer than 2048 characters.');
                continue;
            }
            if (substr_count($url, '*') > 1 || (strpos($url, '*') !== false && substr($url, -1) !== '*')) {
                $errors[] = sprintf($this->l('Invalid wildcard URL: %s'), $url);
                continue;
            }
            $normalizedForParsing = str_replace('*', 'placeholder', $url);
            $parts = parse_url($normalizedForParsing);
            if ($parts === false || !isset($parts['scheme'], $parts['host'])
                || !in_array(strtolower((string) $parts['scheme']), ['http', 'https'], true)
                || isset($parts['user'], $parts['pass'], $parts['port'], $parts['query'], $parts['fragment'])) {
                $errors[] = sprintf($this->l('Invalid bypass URL: %s'), $url);
                continue;
            }
            $host = strtolower((string) $parts['host']);
            if (!preg_match('/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/', $host)
                || ($zoneName !== '' && !$this->isHostInZone($host, $zoneName))) {
                $errors[] = sprintf($this->l('The bypass URL host must belong to the configured zone: %s'), $url);
                continue;
            }
            $urls[] = $url;
        }

        return array_values(array_unique($urls));
    }

    /**
     * Determines whether a hostname is the selected zone or one of its subdomains.
     *
     * @param string $host Submitted hostname
     * @param string $zoneName Selected zone hostname
     *
     * @return bool Whether the hostname belongs to the zone
     */
    private function isHostInZone($host, $zoneName)
    {
        return $host === $zoneName || substr($host, -strlen('.' . $zoneName)) === '.' . $zoneName;
    }

    /**
     * Validates a public URL used only to inspect Cloudflare cache headers.
     *
     * @param string $url Submitted monitor URL
     * @param string $zoneName Configured Cloudflare zone name
     * @param string[] $errors Validation errors appended by reference
     *
     * @return string Normalized monitor URL or an empty string
     */
    private function validateMonitorUrl($url, $zoneName, &$errors)
    {
        if ($url === '') {
            return '';
        }
        if (strlen($url) > 2048 || strpos($url, '*') !== false || preg_match('/[\x00-\x1F\x7F]/', $url)) {
            $errors[] = $this->l('The cache status URL is invalid.');

            return '';
        }
        $parts = parse_url($url);
        if ($parts === false || !isset($parts['scheme'], $parts['host'])
            || !in_array(strtolower((string) $parts['scheme']), ['http', 'https'], true)
            || isset($parts['user'], $parts['pass'], $parts['port'], $parts['fragment'])) {
            $errors[] = $this->l('The cache status URL must be an absolute HTTP or HTTPS URL without credentials or a port.');

            return '';
        }
        $host = strtolower((string) $parts['host']);
        if (!preg_match('/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/', $host)
            || ($zoneName !== '' && !$this->isHostInZone($host, $zoneName))) {
            $errors[] = $this->l('The cache status URL host must belong to the configured zone.');

            return '';
        }

        return $url;
    }

    /**
     * Checks whether the current shop hostname belongs to the selected zone.
     *
     * @return bool Whether the Back Office exclusion can safely be applied
     */
    private function isCurrentStoreInConfiguredZone()
    {
        $zoneName = (string) Configuration::get(self::CFG_ZONE_NAME);
        $storeUrl = $this->context->link->getBaseLink();
        $host = parse_url($storeUrl, PHP_URL_HOST);

        return $zoneName !== '' && is_string($host) && $this->isHostInZone(strtolower($host), strtolower($zoneName));
    }

    /**
     * Returns normalized bypass URLs stored in configuration.
     *
     * @return string[] URL patterns
     */
    private function getConfiguredUrls()
    {
        return array_values(array_filter(preg_split('/\R/', (string) Configuration::get(self::CFG_BYPASS_URLS))));
    }

    /**
     * Escapes a literal for a Cloudflare Rules language string expression.
     *
     * @param string $value Untrusted literal value
     *
     * @return string Escaped literal
     */
    private function escapeExpressionString($value)
    {
        return str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
    }

    /**
     * Renders module settings using PrestaShop's cross-version form helper.
     *
     * @return string Back-office form HTML
     */
    private function renderConfigurationForm()
    {
        $helper = new HelperForm();
        $helper->show_toolbar = false;
        $helper->table = $this->table;
        $helper->module = $this;
        $helper->identifier = $this->identifier;
        $helper->submit_action = 'tec_cf_save';
        $helper->currentIndex = AdminController::$currentIndex . '&configure=' . $this->name;
        $helper->token = Tools::getAdminTokenLite('AdminModules');
        $helper->fields_value = $this->getFormValues();

        return $helper->generateForm([
            $this->buildConnectionForm(),
            $this->buildSynchronizationForm(),
            $this->buildRulesForm(),
            $this->buildPurgeForm(),
        ]);
    }

    /**
     * Returns connection form settings.
     *
     * @return array<string, mixed> HelperForm definition
     */
    private function buildConnectionForm()
    {
        return [
            'form' => [
                'legend' => ['title' => $this->l('Cloudflare connection'), 'icon' => 'icon-cloud'],
                'input' => [
                    ['type' => 'text', 'label' => $this->l('API Token'), 'name' => 'TECCFC_TOKEN', 'required' => false, 'desc' => $this->l('Use a scoped Cloudflare API Token. The saved value is masked.')],
                    ['type' => 'text', 'label' => $this->l('Zone ID'), 'name' => 'TECCFC_ZONE_ID', 'maxlength' => 32, 'required' => false],
                    ['type' => 'text', 'label' => $this->l('Zone name'), 'name' => 'TECCFC_ZONE_NAME', 'maxlength' => 253, 'required' => false, 'desc' => $this->l('Example: example.com. It validates the bypass URL host names.')],
                    ['type' => 'text', 'label' => $this->l('Cache status URL'), 'name' => 'TECCFC_MONITOR_URL', 'maxlength' => 2048, 'required' => false, 'desc' => $this->l('Optional public URL in the selected Cloudflare zone used by Test storefront cache. Leave empty to check the current PrestaShop storefront.')],
                ],
                'submit' => ['title' => $this->l('Save'), 'name' => 'tec_cf_save'],
                'buttons' => [['title' => $this->l('Test connection'), 'name' => 'tec_cf_test', 'type' => 'submit', 'icon' => 'process-icon-refresh']],
            ],
        ];
    }

    /**
     * Returns PrestaShop cache synchronization settings.
     *
     * @return array<string, mixed> HelperForm definition
     */
    private function buildSynchronizationForm()
    {
        return [
            'form' => [
                'legend' => ['title' => $this->l('PrestaShop cache synchronization'), 'icon' => 'icon-refresh'],
                'input' => [[
                    'type' => 'switch',
                    'label' => $this->l('Purge Cloudflare when PrestaShop cache is cleared'),
                    'name' => 'TECCFC_SYNC_WITH_PS',
                    'is_bool' => true,
                    'values' => [['id' => 'sync_on', 'value' => 1, 'label' => $this->l('Enabled')], ['id' => 'sync_off', 'value' => 0, 'label' => $this->l('Disabled')]],
                    'desc' => $this->l('Cloudflare errors never block the native PrestaShop cache clear.'),
                ]],
                'submit' => ['title' => $this->l('Save'), 'name' => 'tec_cf_save'],
            ],
        ];
    }

    /**
     * Returns cache bypass rule settings.
     *
     * @return array<string, mixed> HelperForm definition
     */
    private function buildRulesForm()
    {
        return [
            'form' => [
                'legend' => ['title' => $this->l('Rule Manager'), 'icon' => 'icon-shield'],
                'input' => [
                    ['type' => 'switch', 'label' => $this->l('Exclude PrestaShop Back Office'), 'name' => 'TECCFC_BYPASS_ADMIN', 'is_bool' => true, 'values' => [['id' => 'admin_on', 'value' => 1, 'label' => $this->l('Enabled')], ['id' => 'admin_off', 'value' => 0, 'label' => $this->l('Disabled')]]],
                    ['type' => 'textarea', 'label' => $this->l('Bypass URLs'), 'name' => 'TECCFC_BYPASS_URLS', 'cols' => 70, 'rows' => 8, 'desc' => $this->l('One absolute HTTP or HTTPS URL per line. A wildcard is allowed only at the end of the path, for example https://www.example.com/mag/*.')],
                ],
                'submit' => ['title' => $this->l('Save'), 'name' => 'tec_cf_save'],
                'buttons' => [['title' => $this->l('Apply bypass rules'), 'name' => 'tec_cf_apply_rules', 'type' => 'submit', 'icon' => 'process-icon-save']],
            ],
        ];
    }

    /**
     * Returns the manual cache purge form.
     *
     * @return array<string, mixed> HelperForm definition
     */
    private function buildPurgeForm()
    {
        return [
            'form' => [
                'legend' => ['title' => $this->l('Cache purge'), 'icon' => 'icon-trash'],
                'description' => $this->l('Last status: ') . ((string) Configuration::get(self::CFG_LAST_STATUS) ?: $this->l('No Cloudflare operation has been recorded.')),
                'submit' => ['title' => $this->l('Purge everything'), 'name' => 'tec_cf_purge', 'class' => 'btn btn-warning'],
                'buttons' => [['title' => $this->l('Test storefront cache'), 'name' => 'tec_cf_monitor', 'type' => 'submit', 'icon' => 'process-icon-refresh']],
            ],
        ];
    }

    /**
     * Returns form values while masking the stored API token.
     *
     * @return array<string, mixed> Form values
     */
    private function getFormValues()
    {
        $token = (string) Configuration::get(self::CFG_TOKEN);

        return [
            'TECCFC_TOKEN' => $token === '' ? '' : self::TOKEN_MASK . substr($token, -4),
            'TECCFC_ZONE_ID' => (string) Configuration::get(self::CFG_ZONE_ID),
            'TECCFC_ZONE_NAME' => (string) Configuration::get(self::CFG_ZONE_NAME),
            'TECCFC_SYNC_WITH_PS' => (int) Configuration::get(self::CFG_SYNC_WITH_PS),
            'TECCFC_BYPASS_ADMIN' => (int) Configuration::get(self::CFG_BYPASS_ADMIN),
            'TECCFC_BYPASS_URLS' => (string) Configuration::get(self::CFG_BYPASS_URLS),
            'TECCFC_MONITOR_URL' => (string) Configuration::get(self::CFG_MONITOR_URL),
        ];
    }

    /**
     * Creates an API client from validated stored configuration.
     *
     * @return TecCloudflareCacheClient API client
     */
    private function getClient()
    {
        return new TecCloudflareCacheClient((string) Configuration::get(self::CFG_TOKEN), (string) Configuration::get(self::CFG_ZONE_ID));
    }

    /**
     * Checks whether a Cloudflare API call can be attempted.
     *
     * @return bool Whether credentials are present
     */
    private function isCloudflareConfigured()
    {
        return (string) Configuration::get(self::CFG_TOKEN) !== '' && (string) Configuration::get(self::CFG_ZONE_ID) !== '';
    }

    /**
     * Displays all validation errors using PrestaShop's admin UI.
     *
     * @param string[] $errors Error messages
     *
     * @return string Rendered error markup
     */
    private function formatErrors($errors)
    {
        $output = '';
        foreach ($errors as $error) {
            $output .= $this->displayError($error);
        }

        return $output;
    }

    /**
     * Adds a redacted operation message to PrestaShop logs.
     *
     * @param string $message Safe diagnostic message
     * @param int $severity PrestaShop log severity
     *
     * @return void
     */
    private function log($message, $severity)
    {
        PrestaShopLogger::addLog('Tec Cloudflare Cache: ' . substr($message, 0, 500), $severity, null, 'Teccloudflarecache', (int) $this->id, true);
    }

    /**
     * Removes control characters from a transport diagnostic.
     *
     * @param string $message Raw transport error
     *
     * @return string Safe diagnostic message
     */
    private function sanitizeDiagnostic($message)
    {
        return preg_replace('/[^A-Za-z0-9 .,:;()_-]/', '', substr($message, 0, 180));
    }
}
